"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Language = "en" | "th";

type I18nContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Main",
    openMenu: "Open navigation menu",
    register: "Register",
    myRegistration: "My Registration",
    adminConsole: "Admin Console",
    mainEyebrow: "Event command center",
    mainTitle: "CMD AI Adoption Exam 2026",
    mainLead: "Choose the workflow you need. Registration, attendee edits, and admin review stay in one secure event system.",
    mainRegisterTitle: "New registration",
    mainRegisterText: "Submit attendee details, choose ticket type, attach files, and receive a reference code.",
    mainLookupTitle: "Manage registration",
    mainLookupText: "Check your reference code, unlock with password, and update details or uploaded files.",
    mainAdminTitle: "Admin review",
    mainAdminText: "Sign in to review attendees, update status, inspect files, and download name tag PDFs.",
    openWorkflow: "Open",
    registrationEyebrow: "Event registration",
    registrationTitle: "Register for CMD AI Adoption Exam 2026",
    registrationLead: "Submit your details, attach files, and receive a secure reference code for later edits.",
    secureReturn: "Secure return",
    secureReturnText: "Reference code plus password protects edits.",
    multipleFiles: "Multiple files",
    multipleFilesText: "PDF, JPG, PNG, and DOCX files accepted.",
    adminReady: "Admin ready",
    adminReadyText: "Review details and download name tag PDFs.",
    lookupEyebrow: "Attendee portal",
    lookupTitle: "Manage your registration",
    lookupLead: "Use your reference code first. Password unlock appears only after the code is found.",
    adminEyebrow: "Operations",
    adminTitle: "Admin Console",
    adminLead: "Review registrations, inspect uploaded files, update status, and export name tags.",
    accessSubmission: "Access your submission",
    lookupMeta: "Enter the reference code issued after registration.",
    referenceCode: "Reference code",
    password: "Password",
    enterReferenceFirst: "Enter your reference code first.",
    referenceNotFound: "Reference code was not found.",
    enterRegistrationPassword: "Enter the password for this registration.",
    registrationNotFound: "Registration not found",
    unableFindRegistration: "Unable to find registration.",
    checking: "Checking...",
    unlockSubmission: "Unlock submission",
    checkReferenceCode: "Check reference code",
    adminLoginTitle: "Sign in to Admin Console",
    adminLoginMeta: "Credentials are read from environment variables.",
    username: "Username",
    enterAdminUsername: "Enter the admin username.",
    enterAdminPassword: "Enter the admin password.",
    adminLoginFailed: "Admin login failed",
    invalidAdminCredentials: "Username or password is incorrect.",
    unableLogin: "Unable to log in.",
    unableLoadRegistrations: "Unable to load registrations",
    tryAgain: "Please try again.",
    signingIn: "Signing in...",
    signIn: "Sign in",
    noRecentSubmission: "No recent submission",
    submitToReceiveCode: "Submit a registration to receive a reference code.",
    startRegistration: "Start registration",
    registrationReceived: "Registration received",
    keepReference: "Keep this reference code for edits and event support.",
    documentsUploaded: "uploaded",
    useCodeWithPassword: "Use this code with your password to view or edit your submission.",
    manageLater: "Manage later",
    noRegistrationLoaded: "No registration loaded",
    useReferenceBeforeEditing: "Use your reference code and password before editing.",
    goToMyRegistration: "Go to My Registration",
    editEyebrow: "Attendee portal",
    editTitle: "Review and update your submission",
    editLead: "You can change details, add files, or replace the full file set.",
    modalOk: "OK",
    closeDialog: "Close dialog",
    attendeeDetails: "Attendee details",
    editSubmission: "Edit submission",
    requiredUsage: "All required fields are used for admission, name tag, and event communications.",
    fullName: "Full name",
    email: "Email",
    phone: "Phone",
    organization: "Organization",
    jobTitle: "Job title",
    ticketType: "Ticket type",
    dietaryNeeds: "Food allergies",
    accessibilityNeeds: "Accessibility needs",
    notes: "Additional notes",
    documents: "Choose files",
    phoneHint: "Numbers only, 9 to 15 digits. Do not include spaces, dashes, or +.",
    documentHint: "Upload PDF, PNG, JPG, or DOCX files. Each file can be up to 8 MB.",
    uploadFiles: "Upload files",
    clickToChoose: "Click the field to choose one or more files",
    filesSelected: "files selected",
    documentMode: "Document update mode",
    appendDocuments: "Add uploaded documents to current file set",
    replaceDocuments: "Replace current documents with uploaded files",
    setPassword: "Set password",
    confirmPassword: "Confirm password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    passwordHint: "At least 8 characters, with one letter and one number.",
    submitRegistration: "Submit registration",
    saveChanges: "Save changes",
    saving: "Saving...",
    attachedDocuments: "Documents are attached to this registration record.",
    fixHighlighted: "Please fix the highlighted fields",
    registrationNotSaved: "Registration not saved",
    registrationUpdated: "Registration updated",
    updateSaved: "Your latest details and document changes have been saved.",
    reviewStatus: "Review status",
    reviewDashboard: "Review dashboard",
    totalSubmissions: "total submissions",
    refresh: "Refresh",
    signOut: "Sign out",
    attendeeQueue: "Attendee queue",
    queueSearchHelp: "Search by name, email, company, code, ticket, or status.",
    searchRegistrations: "Search registrations",
    loadingRegistrations: "Loading registrations...",
    noRegistrations: "No registrations match this view.",
    attendeeProfile: "Attendee profile",
    personalInfo: "Personal information",
    eventInfo: "Event information",
    attendeeNeeds: "Needs and notes",
    reviewControl: "Review control",
    selectSubmission: "Select a submission",
    selectToReview: "Select a registration to review details.",
    tagPdf: "Tag PDF",
    name: "Name",
    ticket: "Ticket",
    dietary: "Food allergies",
    accessibility: "Accessibility",
    supportingDocuments: "Uploaded files",
    download: "Download",
    statusNotUpdated: "Status not updated",
    statusUpdated: "Status updated",
    statusUpdatedTo: "is now marked",
    statusSubmitted: "Submitted",
    statusReviewing: "Reviewing",
    statusApproved: "Approved",
    signedOut: "Signed out",
    sessionClosed: "Admin session has been closed.",
    none: "None",
  },
  th: {
    home: "หน้าหลัก",
    openMenu: "เปิดเมนูนำทาง",
    register: "ลงทะเบียน",
    myRegistration: "ข้อมูลลงทะเบียนของฉัน",
    adminConsole: "แผงผู้ดูแล",
    mainEyebrow: "ศูนย์จัดการงาน",
    mainTitle: "CMD AI Adoption Exam 2026",
    mainLead: "เลือกขั้นตอนที่ต้องการใช้งาน ทั้งลงทะเบียน แก้ไขข้อมูลผู้เข้าร่วม และตรวจสอบรายการในระบบเดียว",
    mainRegisterTitle: "ลงทะเบียนใหม่",
    mainRegisterText: "กรอกข้อมูลผู้เข้าร่วม เลือกประเภทบัตร แนบไฟล์ และรับรหัสอ้างอิง",
    mainLookupTitle: "จัดการข้อมูลลงทะเบียน",
    mainLookupText: "ตรวจรหัสอ้างอิงก่อน จากนั้นปลดล็อกด้วยรหัสผ่านเพื่อแก้ไขข้อมูลหรือไฟล์",
    mainAdminTitle: "ตรวจสอบโดยผู้ดูแล",
    mainAdminText: "เข้าสู่ระบบเพื่อดูผู้เข้าร่วม เปลี่ยนสถานะ ตรวจไฟล์ และดาวน์โหลดป้าย PDF",
    openWorkflow: "เปิดใช้งาน",
    registrationEyebrow: "ลงทะเบียนงาน",
    registrationTitle: "ลงทะเบียน CMD AI Adoption Exam 2026",
    registrationLead: "กรอกข้อมูล แนบไฟล์ และรับรหัสอ้างอิงสำหรับกลับมาแก้ไขภายหลัง",
    secureReturn: "กลับมาแก้ไขได้ปลอดภัย",
    secureReturnText: "ใช้รหัสอ้างอิงร่วมกับรหัสผ่านเพื่อป้องกันการแก้ไข",
    multipleFiles: "แนบได้หลายไฟล์",
    multipleFilesText: "รองรับไฟล์ PDF, JPG, PNG และ DOCX",
    adminReady: "พร้อมสำหรับผู้ดูแล",
    adminReadyText: "ตรวจสอบรายละเอียดและดาวน์โหลดป้ายชื่อ PDF ได้ทันที",
    lookupEyebrow: "พอร์ทัลผู้เข้าร่วม",
    lookupTitle: "จัดการข้อมูลลงทะเบียน",
    lookupLead: "กรอกรหัสอ้างอิงก่อน ช่องรหัสผ่านจะแสดงเมื่อพบรหัสในระบบเท่านั้น",
    adminEyebrow: "ระบบปฏิบัติการ",
    adminTitle: "แผงผู้ดูแล",
    adminLead: "ตรวจรายการลงทะเบียน ดูไฟล์ที่อัปโหลด เปลี่ยนสถานะ และดาวน์โหลดป้ายชื่อ",
    accessSubmission: "เข้าสู่ข้อมูลลงทะเบียน",
    lookupMeta: "กรอกรหัสอ้างอิงที่ได้รับหลังลงทะเบียน",
    referenceCode: "รหัสอ้างอิง",
    password: "รหัสผ่าน",
    enterReferenceFirst: "กรุณากรอกรหัสอ้างอิงก่อน",
    referenceNotFound: "ไม่พบรหัสอ้างอิงนี้ในระบบ",
    enterRegistrationPassword: "กรุณากรอกรหัสผ่านของรายการลงทะเบียนนี้",
    registrationNotFound: "ไม่พบข้อมูลลงทะเบียน",
    unableFindRegistration: "ไม่สามารถค้นหาข้อมูลลงทะเบียนได้",
    checking: "กำลังตรวจสอบ...",
    unlockSubmission: "ปลดล็อกข้อมูล",
    checkReferenceCode: "ตรวจรหัสอ้างอิง",
    adminLoginTitle: "เข้าสู่ระบบผู้ดูแล",
    adminLoginMeta: "ข้อมูลเข้าสู่ระบบอ่านจาก environment variables",
    username: "ชื่อผู้ใช้",
    enterAdminUsername: "กรุณากรอกชื่อผู้ใช้ผู้ดูแล",
    enterAdminPassword: "กรุณากรอกรหัสผ่านผู้ดูแล",
    adminLoginFailed: "เข้าสู่ระบบผู้ดูแลไม่สำเร็จ",
    invalidAdminCredentials: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    unableLogin: "ไม่สามารถเข้าสู่ระบบได้",
    unableLoadRegistrations: "โหลดรายการลงทะเบียนไม่ได้",
    tryAgain: "กรุณาลองอีกครั้ง",
    signingIn: "กำลังเข้าสู่ระบบ...",
    signIn: "เข้าสู่ระบบ",
    noRecentSubmission: "ยังไม่มีข้อมูลที่เพิ่งส่ง",
    submitToReceiveCode: "ลงทะเบียนเพื่อรับรหัสอ้างอิง",
    startRegistration: "เริ่มลงทะเบียน",
    registrationReceived: "รับข้อมูลลงทะเบียนแล้ว",
    keepReference: "เก็บรหัสอ้างอิงนี้ไว้สำหรับแก้ไขข้อมูลและติดต่อทีมงาน",
    documentsUploaded: "ไฟล์ที่อัปโหลด",
    useCodeWithPassword: "ใช้รหัสนี้ร่วมกับรหัสผ่านเพื่อดูหรือแก้ไขข้อมูลลงทะเบียน",
    manageLater: "จัดการภายหลัง",
    noRegistrationLoaded: "ยังไม่มีข้อมูลลงทะเบียนที่โหลดไว้",
    useReferenceBeforeEditing: "ใช้รหัสอ้างอิงและรหัสผ่านก่อนเข้าแก้ไขข้อมูล",
    goToMyRegistration: "ไปที่ข้อมูลลงทะเบียนของฉัน",
    editEyebrow: "พอร์ทัลผู้เข้าร่วม",
    editTitle: "ตรวจสอบและแก้ไขข้อมูล",
    editLead: "แก้ไขรายละเอียด เพิ่มไฟล์ หรือแทนที่ชุดไฟล์ทั้งหมดได้",
    modalOk: "ตกลง",
    closeDialog: "ปิดหน้าต่าง",
    attendeeDetails: "ข้อมูลผู้เข้าร่วม",
    editSubmission: "แก้ไขข้อมูลลงทะเบียน",
    requiredUsage: "ข้อมูลที่จำเป็นใช้สำหรับการเข้างาน ป้ายชื่อ และการติดต่อจากทีมงาน",
    fullName: "ชื่อ-นามสกุล",
    email: "อีเมล",
    phone: "เบอร์โทร",
    organization: "องค์กร",
    jobTitle: "ตำแหน่งงาน",
    ticketType: "ประเภทบัตร",
    dietaryNeeds: "ข้อมูลแพ้อาหาร",
    accessibilityNeeds: "ความช่วยเหลือพิเศษ",
    notes: "หมายเหตุเพิ่มเติม",
    documents: "เลือกไฟล์",
    phoneHint: "ใส่เฉพาะตัวเลข 9-15 หลัก ห้ามมีเว้นวรรค ขีด หรือเครื่องหมาย +",
    documentHint: "อัปโหลดไฟล์ PDF, PNG, JPG หรือ DOCX ขนาดไม่เกิน 8 MB ต่อไฟล์",
    uploadFiles: "อัปโหลดไฟล์",
    clickToChoose: "กดที่ช่องนี้เพื่อเลือกไฟล์หนึ่งไฟล์หรือหลายไฟล์",
    filesSelected: "ไฟล์ที่เลือก",
    documentMode: "วิธีจัดการเอกสาร",
    appendDocuments: "เพิ่มเอกสารใหม่ต่อจากชุดเดิม",
    replaceDocuments: "แทนที่เอกสารเดิมทั้งหมดด้วยไฟล์ใหม่",
    setPassword: "ตั้งรหัสผ่าน",
    confirmPassword: "ยืนยันรหัสผ่าน",
    showPassword: "แสดงรหัสผ่าน",
    hidePassword: "ซ่อนรหัสผ่าน",
    passwordHint: "อย่างน้อย 8 ตัวอักษร และต้องมีตัวอักษรกับตัวเลข",
    submitRegistration: "ส่งข้อมูลลงทะเบียน",
    saveChanges: "บันทึกการแก้ไข",
    saving: "กำลังบันทึก...",
    attachedDocuments: "เอกสารถูกแนบไว้กับข้อมูลลงทะเบียนนี้",
    fixHighlighted: "กรุณาแก้ไขช่องที่ถูกไฮไลต์",
    registrationNotSaved: "ยังบันทึกข้อมูลไม่ได้",
    registrationUpdated: "อัปเดตข้อมูลแล้ว",
    updateSaved: "บันทึกรายละเอียดและเอกสารล่าสุดเรียบร้อยแล้ว",
    reviewStatus: "สถานะการตรวจสอบ",
    reviewDashboard: "แดชบอร์ดตรวจสอบ",
    totalSubmissions: "รายการลงทะเบียนทั้งหมด",
    refresh: "รีเฟรช",
    signOut: "ออกจากระบบ",
    attendeeQueue: "คิวผู้เข้าร่วม",
    queueSearchHelp: "ค้นหาด้วยชื่อ อีเมล บริษัท รหัส ประเภทบัตร หรือสถานะ",
    searchRegistrations: "ค้นหารายการลงทะเบียน",
    loadingRegistrations: "กำลังโหลดรายการ...",
    noRegistrations: "ไม่พบรายการที่ตรงกับเงื่อนไข",
    attendeeProfile: "โปรไฟล์ผู้เข้าร่วม",
    personalInfo: "ข้อมูลส่วนตัว",
    eventInfo: "ข้อมูลงานและบัตร",
    attendeeNeeds: "ความต้องการเพิ่มเติม",
    reviewControl: "การตรวจสอบ",
    selectSubmission: "เลือกรายการลงทะเบียน",
    selectToReview: "เลือกรายการลงทะเบียนเพื่อดูรายละเอียด",
    tagPdf: "ดาวน์โหลดป้าย PDF",
    name: "ชื่อ",
    ticket: "บัตร",
    dietary: "แพ้อาหาร",
    accessibility: "ความช่วยเหลือ",
    supportingDocuments: "ไฟล์ที่อัปโหลด",
    download: "ดาวน์โหลด",
    statusNotUpdated: "ยังอัปเดตสถานะไม่ได้",
    statusUpdated: "อัปเดตสถานะแล้ว",
    statusUpdatedTo: "ถูกเปลี่ยนสถานะเป็น",
    statusSubmitted: "ส่งข้อมูลแล้ว",
    statusReviewing: "กำลังตรวจสอบ",
    statusApproved: "อนุมัติแล้ว",
    signedOut: "ออกจากระบบแล้ว",
    sessionClosed: "ปิด session ผู้ดูแลเรียบร้อยแล้ว",
    none: "ไม่มี",
  },
};

const I18nContext = createContext<I18nContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const stored = window.localStorage.getItem("cmd-event-language");
    if (stored === "th" || stored === "en") setLanguageState(stored);
  }, []);

  const value = useMemo<I18nContextValue>(() => {
    return {
      language,
      setLanguage: (nextLanguage) => {
        setLanguageState(nextLanguage);
        window.localStorage.setItem("cmd-event-language", nextLanguage);
      },
      t: (key) => translations[language][key] || translations.en[key] || key,
    };
  }, [language]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const context = useContext(I18nContext);
  if (!context) throw new Error("useI18n must be used within LanguageProvider");
  return context;
}

export function translateServerError(message: string, language: Language): string {
  if (language === "en") return message;

  const map: Record<string, string> = {
    "Enter the attendee full name.": "กรุณากรอกชื่อ-นามสกุลผู้เข้าร่วม",
    "Full name must be 80 characters or less.": "ชื่อ-นามสกุลต้องไม่เกิน 80 ตัวอักษร",
    "Enter a valid email address, for example name@example.com.": "กรุณากรอกอีเมลให้ถูกต้อง เช่น name@example.com",
    "Phone must contain numbers only, 9 to 15 digits.": "เบอร์โทรต้องเป็นตัวเลขเท่านั้น ความยาว 9-15 หลัก",
    "Enter the attendee organization.": "กรุณากรอกชื่อองค์กร",
    "Organization must be 100 characters or less.": "ชื่อองค์กรต้องไม่เกิน 100 ตัวอักษร",
    "Enter the attendee job title.": "กรุณากรอกตำแหน่งงาน",
    "Job title must be 80 characters or less.": "ตำแหน่งงานต้องไม่เกิน 80 ตัวอักษร",
    "Choose a valid ticket type.": "กรุณาเลือกประเภทบัตรให้ถูกต้อง",
    "Password must be at least 8 characters.": "รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร",
    "Password must include at least one letter and one number.": "รหัสผ่านต้องมีตัวอักษรและตัวเลขอย่างน้อยอย่างละหนึ่งตัว",
    "Food allergies must be 120 characters or less.": "ข้อมูลแพ้อาหารต้องไม่เกิน 120 ตัวอักษร",
    "Accessibility needs must be 120 characters or less.": "ข้อมูลความช่วยเหลือพิเศษต้องไม่เกิน 120 ตัวอักษร",
    "Notes must be 800 characters or less.": "หมายเหตุต้องไม่เกิน 800 ตัวอักษร",
    "Choose at least one file.": "กรุณาเลือกไฟล์อย่างน้อยหนึ่งไฟล์",
    "Upload at least one supporting document.": "กรุณาเลือกไฟล์อย่างน้อยหนึ่งไฟล์",
    "Uploaded documents cannot be empty.": "ไฟล์เอกสารต้องไม่เป็นไฟล์ว่าง",
    "Each document must be 8 MB or smaller.": "เอกสารแต่ละไฟล์ต้องมีขนาดไม่เกิน 8 MB",
    "Documents must be PDF, PNG, JPG, or DOCX.": "เอกสารต้องเป็นไฟล์ PDF, PNG, JPG หรือ DOCX",
  };

  return map[message] || message;
}
